### ISSUE TITLE
Its an issue? i can't launch the game with hodgepodge enabled

### ISSUE THREAD

**Issue by quentin452** [makamys/GTNHMixinsLite#1]
mods list : 

00gasstation-mc1.7.10-0.5.1
falsepatternlib-mc1.7.10-0.10.14
gtnhmixinslite-2.1.4-lite_1
hodgepodge-1.7.10-2.0.11

logs : 

https://paste.ee/p/JLdA9

note :
 
Hodgepodge require gtnh mixins 2.0+

**Comment by kotmatross28729** [comment]
as far as i know gtnh mixins use library "GTNHLib" to work
(https://github.com/GTNewHorizons/GTNHLib)
try to install and tell  if it helps, In my modpack it works

**Comment by quentin452** [comment]
thx is work
